### ISSUE TITLE
[BUG] 通量升级能量显示错误

### ISSUE THREAD

**Issue by KLONOA9X6** [Minecraft-LightLand/L2Archery#5]
![image](https://github.com/Minecraft-LightLand/L2Archery/assets/95112579/ca902baf-f81b-4505-b263-4d45fd15207d)
如图所示，在弓敲上通量升级后，能量条的渲染不正常（图标左上的黑色区域）
（非兼容性问题，下载源码后在开发环境下也会出现）

**Comment by lcy0x1** [comment]
版本？1.20吗

**Comment by lcy0x1** [comment]
修好了

**Comment by KLONOA9X6** [comment]
这么快？

**Comment by lcy0x1** [comment]
1.19到1.20的渲染代码的含义从x,y,w,h变成了x0,y0,x1,y1我没注意到，改一下就好了
