### ISSUE TITLE
L2 Archery bows are incompatable with arrows from the BetterDefaultBiomes mod 2.4.13

### ISSUE THREAD

**Issue by Sageking10** [Minecraft-LightLand/L2Archery#6]
Arrows from the betterdefaultbiomes mod aren't compatible with bows from this mod. 
![2024-03-17_17 43 13](https://github.com/Minecraft-LightLand/L2Archery/assets/48606472/3b84ae97-b133-433f-9c4a-dfc2df2c6b3f)
![2024-03-17_17 42 25](https://github.com/Minecraft-LightLand/L2Archery/assets/48606472/9370002b-a62e-4718-9867-6a5e2d536e60)

**Comment by lcy0x1** [comment]
As expected. Both mod requires their own Arrow Entity, and there are no ways to merge them. If you think my arrows left some use cases uncovered, feel free to suggest.
